#!/usr/bin/env bash


export AWS_PROFILE=6Pages
export AWS_REGION=us-east-1


export AWS_LAMBDA_FN_NAME=lacinia-api
export AWS_LAMBDA_HANDLER="com.sixpages.lacinia-api.handler"

export TARGET_PATH=target
export TARGET_NAME=lacinia-api-0.0.1-SNAPSHOT-standalone.jar
