#!/usr/bin/env bash

hash realpath 2>/dev/null || { echo >&2 "this script requires \"realpath\" but it's not installed.  Please install it and try again."; exit 1; }

export SCRIPT_PATH=$(dirname $(realpath "$0"))
export CURRENT_PATH=$(cd "`dirname "0"`" && pwd)
export BASE_PATH=$SCRIPT_PATH/..
